            - name: Setup Bun
  # You may pin to the exact commit or the version.
  # uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5
  uses: oven-sh/setup-bun@v2
  with:
    # The version of Bun to install. (e.g. "latest", "canary", "1.0.0", "1.0.x", <sha>)
    bun-version: # optional
    # The version of Bun to install from file. (e.g. "package.json", ".bun-version", ".tool-versions")
    bun-version-file: # optional
    # Override the URL to download Bun from. This skips version resolution and verifying AVX2 support.
    bun-download-url: # optional
    # The URL of the package registry to use for installing Bun. Set the $BUN_AUTH_TOKEN environment variable to authenticate with the registry.
    registry-url: # optional
    # The scope for authenticating with the package registry.
    scope: # optional
    # Disable caching of bun executable.
    no-cache: # optional
          
